### Register a new user
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "whitneynavalia@gmail.com",
    "password": "Passwordwww",
    "name": "whit"
    
}


### Register a new super-admin user
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "marvo2@gmail.com",
    "password": "marvo@MIX",
    "name": "Admin1",
    "role": "SUPER_ADMIN"
}

### Register a new manager user
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "marvo@gmail.com",
    "password": "marvo@MIX",
    "name": "Manager1",
    "role": "EVENT_MANAGER"
}

### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
   
    "email": "testuser899@example.com",
    "password": "Password899999999999"
}

### Login as admin
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "marvo2@gmail.com",
    "password": "marvo@MIX"
}

### Login as manager
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "marvo@gmail.com",
    "password": "marvo@MIX"
}

### Reset Password
POST http://localhost:3000/users/reset
Content-Type: application/json

{
    "email": "testuser@example.com",
    "newPassword": "NewPassword123"
}

### Reset Password
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "testuser@example.com",
    "newPassword": "NewPassword123"
}
