### Register a new user
POST http://localhost:3000/users/register
Content-Type: application/json


{
    "email": "whitneyjacks685@gmail.com",
    "password": "Password123",
    "name": "whit"
    
}


### Register a new super-admin user
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "marvo3@gmail.com",
    "password": "marvo@MIX",
    "name": "Admin1",
    "role": "SUPER_ADMIN"
}


### Register a new manager user
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "marvgffoke@gmail.com",
    "password": "marvokhhu7e@MIX",
    "name": "Manager990",
    "role": "EVENT_MANAGER"
}



### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "proheromarvin@gmail.com",
    "password": "Password123"
    
}



### Login as admin
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "marvo2@gmail.com",
    "password": "marvo@MIX"
}



### Login as manager
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "marvo@gmail.com",
    "password": "marvo@MIX"
}



### Reset Password
POST http://localhost:3000/users/reset
Content-Type: application/json

{
    "email": "testuser@example.com",
    "Password": "NewPassword123"
}



### Reset Password
POST http://localhost:3000/users/reset
Content-Type: application/json

Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJtYXJ2b0BnbWFpbC5jb20iLCJyb2xlIjoiRVZFTlRfTUFOQUdFUiIsImlhdCI6MTcyMTMzODIwOCwiZXhwIjoxNzIxMzQxODA4fQ.ymYoSnihB2sl2h9irE_nD70GcfWsUA68pVMjOt5gPaw

{
   "email": "marvo2@gmail.com",
    "password": "marvo@MINT"
}
